### ISSUE TITLE
Api: /index/info/getMyinfo和/index/report/getlastdata

### ISSUE THREAD

**Issue by huagua** [2020NCOV/MiniProgram-server-Golang#12]
**要求** 
- 根据接口文档实现功能（接口文档见项目主仓库）
- 首先请读懂流程（readme文档）
- 主要逻辑在service/get_info_service.go文件中,(注意这里面包含了getMyinfo和getlastdata的业务逻辑，为避免出现冲突，建议一人实现这两个接口，最好独立出来成两个service服务，所以工作量稍大）
- 参考文档：[gin官方文档](https://github.com/gin-gonic/gin)、[gin中文文档](https://github.com/skyhee/gin-doc-cn)、 [gorm中文文档](http://gorm.io/zh_CN/docs/index.html)

**Comment by Chenxi97** [comment]
I will fix this
