### ISSUE TITLE
Api: /index/login/getcorpname

### ISSUE THREAD

**Issue by huagua** [2020NCOV/MiniProgram-server-Golang#13]
**要求** 
- 根据接口文档实现功能（接口文档见项目主仓库）
- 首先请读懂流程（readme文档）
- 主要逻辑在service/get_corpname_service.go文件中
- 参考文档：[gin官方文档](https://github.com/gin-gonic/gin)、[gin中文文档](https://github.com/skyhee/gin-doc-cn)、 [gorm中文文档](http://gorm.io/zh_CN/docs/index.html)

**Comment by yy-pku** [comment]
杨瑛认领该接口
/self-assign
